###healthcare dataset

library(here)
library(tidyverse)

#set these variables
file_name <- "heart.Rds" 
dataframe_name <- "heart" 
dataframe_title <- "Heart Disease Dataset"
dataframe_source <- "This data set dates from 1988 and consists of four databases: Cleveland, Hungary, Switzerland, and Long Beach V."
dataframe_desc <- "The complete data set contains 76 attributes, including a predicted attribute generated by ML models to predict heart failure. However, all published experiments refer to using a subset of 14 attributes, which we will use for this class"
path_to_data <- here::here("data", file_name)
data <- readRDS(path_to_data)
heart <- data #set this object as the same as datafraem_name, makes it available in the learnr chunks
#heart_joined
#patient_hx