---
title: "adding meds to phx"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
#library(babynames)
```

# Import heart data
```{r}
source(here::here("code", "healthcare.R")) #loads dataset-specific variables
```

# Family history
```{r adding variables}
# Create a "family_history" variable
fam_hist <- c("Aunt", "aunt", "Auntie", "auntie", "Father", "father", "Uncle", "uncle", "Grandmother", "grandmother", "Grandfather", "grandfather", "Mother", "mother")

heart$family_history <- sample(fam_hist, nrow(heart), replace = TRUE) # exercise idea: use Stringr to identify patients whose grandPARENTS have heart disease

# You could also show how to clean up names by standardising
```

# Define drugs
```{r}
#trestbps (high bp)
high_trestbps <- c("felodipine", "isradipine", "amlodipine", NA)

#chol (cholesterol)
high_chol <- c("atorvastatin", "simvastatin", "lovastatin", NA)

#fbs (diabetes)
high_fbs <- c("insulin", "metformin", "glyburide", "glimepiride", "rosiglitazone", NA)

#exang (angina)
high_exang <- c("aspirin", "nitrates", "Metoprolol", "Acebutolol", NA)

#target
#3 of the above

```



```{r}
#functions
high_filler <- function(high_var, drug_class) {}

heart <- heart %>% 
   mutate(drug_trestpbs = map_if(heart$trestbps > 120, sample(high_trestbps, 1)))

heart %>% count(drug_trestpbs, sort = TRUE)
```

Making a new dataframe
```{r new df}
heart <- heart %>% 
          mutate(health_status = case_when(
            fbs == "elevated" & chol > 240 ~ "Diabetic & High Cholesterol",
            fbs == "elevated" ~ "Diabetic",
            chol > 240 ~ "High Cholesterol",
            TRUE ~ "Normal blood sugar and cholesterol"
          ))

```

All of the following code is adapted from Akshay's code to add names/addresses
```{r}
heart %>% count(health_status) 

meds <- tibble::tribble(
   ~Drug, ~Status,
   "metformin", "Diabetes",
   "insulin", "Diabetes",
   "sulfonylurea", "Diabetes",
   "atorvastatin", "High Cholesterol",
   "simvastatin", "High Cholesterol",
   "lovastatin", "High Cholesterol",
   NA, "Diabetes",
   NA, "High Cholesterol"
)

```


```{r}
diabetic<- heart %>% filter(health_status == "Diabetic")
highchol <- heart %>% filter(health_status == "High Cholesterol")

healthy<- heart %>% filter(health_status == "Normal blood sugar and cholesterol")

healthy$medication <- NA
 
diabetic$medication <- meds %>% 
                       filter(Status == "Diabetes") %>% 
                       sample_n(nrow(diabetic), replace = TRUE) %>% 
                       mutate(Drug = str_to_title(Drug)) %>% 
                       pull(Drug)

highchol$medication <- meds %>% 
                       filter(Status == "High Cholesterol") %>% 
                       sample_n(nrow(highchol), replace = TRUE) %>% 
                       mutate(Drug = str_to_title(Drug)) %>% 
                       pull(Drug)

drug1 <- bind_rows(highchol, diabetic)

phx<- bind_rows(healthy, drug1)

phx <- phx %>% select(-healthy)

patient_hx <- patient_hx %>% 
                select(health_status, family_history, medication) %>% 
                rowid_to_column() %>% 
                rename(patientid = rowid)

#write_csv(phx, "phx.csv")


```

